server:  port: 8083

spring:
  cloud:
    gateway:
      routes:
       - id : USER-SERVICE
         uri : lb://USER-SERVICE
         predicates:         - Path=/users/**
         
       
       - id : HOTEL-SERVICE
         uri : lb://HOTEL-SERVICE
         predicates:
         - Path=/hotel/**
         
         
       - id : RATING-SERVICE
         uri : lb://RATING-SERVICE
         predicates:
         - Path=/ratings/**
           application:    name: API-GATEWAY    
eureka:  client:    fetch-registry: true    register-with-eureka: true   
         
      